// Re-export db connection
export { db, testConnection } from '../config/db.js'

// Re-export all schema tables
export * from './schema/users.js'
export * from './schema/roles.js'
export * from './schema/permissions.js'
export * from './schema/items.js'
export * from './schema/categories.js'
export * from './schema/uoms.js'
export * from './schema/suppliers.js'
export * from './schema/warehouses.js'
export * from './schema/racks.js'
export * from './schema/bins.js'
export * from './schema/vendor_price_list.js'
export * from './schema/purchase_requests.js'
export * from './schema/purchase_orders.js'
export * from './schema/goods_receipts.js'
export * from './schema/stocks.js'
export * from './schema/stock_movements.js'
export * from './schema/issue_requests.js'
export * from './schema/goods_issues.js'
export * from './schema/transfers.js'
export * from './schema/stock_opnames.js'
export * from './schema/returns.js'
export * from './schema/audit_logs.js'
